name ="mediumblogapp"
main = "src/index.ts"
compatibility_date = "2024-12-27"

[vars]
DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTk1YTJmMmItODNmYy00ZDgzLWJiNDQtYWM2YzRkNTJmMDI4IiwidGVuYW50X2lkIjoiNDQ4MWJlZTI0ZWUwYzk3NTBhMTdkNGQ5MjI2YTkwZDQyYTIyYWI4ZjQ0ODA3MjQ1ZjUzZDI0ODkyMDgyMjQ5ZCIsImludGVybmFsX3NlY3JldCI6IjNmZGJlZjQxLTIzYzItNDBhZC1hM2I2LWY0MGM1NzU5MTIxMyJ9.gTpdFOOJBk0UViC6k61HyUAwJtbZKedOFVF9-aUIng4"


JWT_SECRET = "secret"
